version: '3.3'

services:
  postgres.db:
    container_name: postgres-yapp
    image: vixx170627/postgres-ko
    restart: unless-stopped
    ports:
      - "54320:5432"
    env_file:
      - .env
    volumes:
      - postgres13.0-data:/var/lib/postgresql/data
  redis:
    container_name: yapp_redis
    image: redis
    restart: unless-stopped
    ports:
      - "63790:6379"

volumes:
  postgres13.0-data: